// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImgFea.proto

package es.fea;

public final class ImgFea {
  private ImgFea() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImFeaArrOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.fea.ImFeaArr)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    java.util.List<es.fea.ImgFea.ImFea> 
        getArrList();
    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    es.fea.ImgFea.ImFea getArr(int index);
    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    int getArrCount();
    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    java.util.List<? extends es.fea.ImgFea.ImFeaOrBuilder> 
        getArrOrBuilderList();
    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    es.fea.ImgFea.ImFeaOrBuilder getArrOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code es.fea.ImFeaArr}
   */
  public  static final class ImFeaArr extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:es.fea.ImFeaArr)
      ImFeaArrOrBuilder {
    // Use ImFeaArr.newBuilder() to construct.
    private ImFeaArr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImFeaArr() {
      arr_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImFeaArr(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                arr_ = new java.util.ArrayList<es.fea.ImgFea.ImFea>();
                mutable_bitField0_ |= 0x00000001;
              }
              arr_.add(
                  input.readMessage(es.fea.ImgFea.ImFea.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          arr_ = java.util.Collections.unmodifiableList(arr_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.fea.ImgFea.internal_static_es_fea_ImFeaArr_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.fea.ImgFea.internal_static_es_fea_ImFeaArr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.fea.ImgFea.ImFeaArr.class, es.fea.ImgFea.ImFeaArr.Builder.class);
    }

    public static final int ARR_FIELD_NUMBER = 1;
    private java.util.List<es.fea.ImgFea.ImFea> arr_;
    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    public java.util.List<es.fea.ImgFea.ImFea> getArrList() {
      return arr_;
    }
    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    public java.util.List<? extends es.fea.ImgFea.ImFeaOrBuilder> 
        getArrOrBuilderList() {
      return arr_;
    }
    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    public int getArrCount() {
      return arr_.size();
    }
    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    public es.fea.ImgFea.ImFea getArr(int index) {
      return arr_.get(index);
    }
    /**
     * <code>repeated .es.fea.ImFea arr = 1;</code>
     */
    public es.fea.ImgFea.ImFeaOrBuilder getArrOrBuilder(
        int index) {
      return arr_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < arr_.size(); i++) {
        output.writeMessage(1, arr_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < arr_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, arr_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof es.fea.ImgFea.ImFeaArr)) {
        return super.equals(obj);
      }
      es.fea.ImgFea.ImFeaArr other = (es.fea.ImgFea.ImFeaArr) obj;

      boolean result = true;
      result = result && getArrList()
          .equals(other.getArrList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getArrCount() > 0) {
        hash = (37 * hash) + ARR_FIELD_NUMBER;
        hash = (53 * hash) + getArrList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static es.fea.ImgFea.ImFeaArr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.fea.ImgFea.ImFeaArr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaArr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.fea.ImgFea.ImFeaArr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaArr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFeaArr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaArr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFeaArr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaArr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFeaArr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(es.fea.ImgFea.ImFeaArr prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.fea.ImFeaArr}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.fea.ImFeaArr)
        es.fea.ImgFea.ImFeaArrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.fea.ImgFea.internal_static_es_fea_ImFeaArr_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.fea.ImgFea.internal_static_es_fea_ImFeaArr_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.fea.ImgFea.ImFeaArr.class, es.fea.ImgFea.ImFeaArr.Builder.class);
      }

      // Construct using es.fea.ImgFea.ImFeaArr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArrFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (arrBuilder_ == null) {
          arr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          arrBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.fea.ImgFea.internal_static_es_fea_ImFeaArr_descriptor;
      }

      public es.fea.ImgFea.ImFeaArr getDefaultInstanceForType() {
        return es.fea.ImgFea.ImFeaArr.getDefaultInstance();
      }

      public es.fea.ImgFea.ImFeaArr build() {
        es.fea.ImgFea.ImFeaArr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.fea.ImgFea.ImFeaArr buildPartial() {
        es.fea.ImgFea.ImFeaArr result = new es.fea.ImgFea.ImFeaArr(this);
        int from_bitField0_ = bitField0_;
        if (arrBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            arr_ = java.util.Collections.unmodifiableList(arr_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.arr_ = arr_;
        } else {
          result.arr_ = arrBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.fea.ImgFea.ImFeaArr) {
          return mergeFrom((es.fea.ImgFea.ImFeaArr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.fea.ImgFea.ImFeaArr other) {
        if (other == es.fea.ImgFea.ImFeaArr.getDefaultInstance()) return this;
        if (arrBuilder_ == null) {
          if (!other.arr_.isEmpty()) {
            if (arr_.isEmpty()) {
              arr_ = other.arr_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArrIsMutable();
              arr_.addAll(other.arr_);
            }
            onChanged();
          }
        } else {
          if (!other.arr_.isEmpty()) {
            if (arrBuilder_.isEmpty()) {
              arrBuilder_.dispose();
              arrBuilder_ = null;
              arr_ = other.arr_;
              bitField0_ = (bitField0_ & ~0x00000001);
              arrBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArrFieldBuilder() : null;
            } else {
              arrBuilder_.addAllMessages(other.arr_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.fea.ImgFea.ImFeaArr parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.fea.ImgFea.ImFeaArr) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<es.fea.ImgFea.ImFea> arr_ =
        java.util.Collections.emptyList();
      private void ensureArrIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          arr_ = new java.util.ArrayList<es.fea.ImgFea.ImFea>(arr_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          es.fea.ImgFea.ImFea, es.fea.ImgFea.ImFea.Builder, es.fea.ImgFea.ImFeaOrBuilder> arrBuilder_;

      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public java.util.List<es.fea.ImgFea.ImFea> getArrList() {
        if (arrBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arr_);
        } else {
          return arrBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public int getArrCount() {
        if (arrBuilder_ == null) {
          return arr_.size();
        } else {
          return arrBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public es.fea.ImgFea.ImFea getArr(int index) {
        if (arrBuilder_ == null) {
          return arr_.get(index);
        } else {
          return arrBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public Builder setArr(
          int index, es.fea.ImgFea.ImFea value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.set(index, value);
          onChanged();
        } else {
          arrBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public Builder setArr(
          int index, es.fea.ImgFea.ImFea.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.set(index, builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public Builder addArr(es.fea.ImgFea.ImFea value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.add(value);
          onChanged();
        } else {
          arrBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public Builder addArr(
          int index, es.fea.ImgFea.ImFea value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.add(index, value);
          onChanged();
        } else {
          arrBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public Builder addArr(
          es.fea.ImgFea.ImFea.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.add(builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public Builder addArr(
          int index, es.fea.ImgFea.ImFea.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.add(index, builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public Builder addAllArr(
          java.lang.Iterable<? extends es.fea.ImgFea.ImFea> values) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, arr_);
          onChanged();
        } else {
          arrBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public Builder clearArr() {
        if (arrBuilder_ == null) {
          arr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          arrBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public Builder removeArr(int index) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.remove(index);
          onChanged();
        } else {
          arrBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public es.fea.ImgFea.ImFea.Builder getArrBuilder(
          int index) {
        return getArrFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public es.fea.ImgFea.ImFeaOrBuilder getArrOrBuilder(
          int index) {
        if (arrBuilder_ == null) {
          return arr_.get(index);  } else {
          return arrBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public java.util.List<? extends es.fea.ImgFea.ImFeaOrBuilder> 
           getArrOrBuilderList() {
        if (arrBuilder_ != null) {
          return arrBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arr_);
        }
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public es.fea.ImgFea.ImFea.Builder addArrBuilder() {
        return getArrFieldBuilder().addBuilder(
            es.fea.ImgFea.ImFea.getDefaultInstance());
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public es.fea.ImgFea.ImFea.Builder addArrBuilder(
          int index) {
        return getArrFieldBuilder().addBuilder(
            index, es.fea.ImgFea.ImFea.getDefaultInstance());
      }
      /**
       * <code>repeated .es.fea.ImFea arr = 1;</code>
       */
      public java.util.List<es.fea.ImgFea.ImFea.Builder> 
           getArrBuilderList() {
        return getArrFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          es.fea.ImgFea.ImFea, es.fea.ImgFea.ImFea.Builder, es.fea.ImgFea.ImFeaOrBuilder> 
          getArrFieldBuilder() {
        if (arrBuilder_ == null) {
          arrBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              es.fea.ImgFea.ImFea, es.fea.ImgFea.ImFea.Builder, es.fea.ImgFea.ImFeaOrBuilder>(
                  arr_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          arr_ = null;
        }
        return arrBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:es.fea.ImFeaArr)
    }

    // @@protoc_insertion_point(class_scope:es.fea.ImFeaArr)
    private static final es.fea.ImgFea.ImFeaArr DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new es.fea.ImgFea.ImFeaArr();
    }

    public static es.fea.ImgFea.ImFeaArr getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ImFeaArr>
        PARSER = new com.google.protobuf.AbstractParser<ImFeaArr>() {
      public ImFeaArr parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ImFeaArr(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImFeaArr> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImFeaArr> getParserForType() {
      return PARSER;
    }

    public es.fea.ImgFea.ImFeaArr getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImFeaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.fea.ImFea)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated double f = 1;</code>
     */
    java.util.List<java.lang.Double> getFList();
    /**
     * <code>repeated double f = 1;</code>
     */
    int getFCount();
    /**
     * <code>repeated double f = 1;</code>
     */
    double getF(int index);
  }
  /**
   * Protobuf type {@code es.fea.ImFea}
   */
  public  static final class ImFea extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:es.fea.ImFea)
      ImFeaOrBuilder {
    // Use ImFea.newBuilder() to construct.
    private ImFea(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImFea() {
      f_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImFea(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                f_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              f_.add(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                f_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                f_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          f_ = java.util.Collections.unmodifiableList(f_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.fea.ImgFea.internal_static_es_fea_ImFea_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.fea.ImgFea.internal_static_es_fea_ImFea_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.fea.ImgFea.ImFea.class, es.fea.ImgFea.ImFea.Builder.class);
    }

    public static final int F_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Double> f_;
    /**
     * <code>repeated double f = 1;</code>
     */
    public java.util.List<java.lang.Double>
        getFList() {
      return f_;
    }
    /**
     * <code>repeated double f = 1;</code>
     */
    public int getFCount() {
      return f_.size();
    }
    /**
     * <code>repeated double f = 1;</code>
     */
    public double getF(int index) {
      return f_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < f_.size(); i++) {
        output.writeDouble(1, f_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getFList().size();
        size += dataSize;
        size += 1 * getFList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof es.fea.ImgFea.ImFea)) {
        return super.equals(obj);
      }
      es.fea.ImgFea.ImFea other = (es.fea.ImgFea.ImFea) obj;

      boolean result = true;
      result = result && getFList()
          .equals(other.getFList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFCount() > 0) {
        hash = (37 * hash) + F_FIELD_NUMBER;
        hash = (53 * hash) + getFList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static es.fea.ImgFea.ImFea parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.fea.ImgFea.ImFea parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFea parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.fea.ImgFea.ImFea parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFea parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFea parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFea parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFea parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFea parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFea parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(es.fea.ImgFea.ImFea prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.fea.ImFea}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.fea.ImFea)
        es.fea.ImgFea.ImFeaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.fea.ImgFea.internal_static_es_fea_ImFea_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.fea.ImgFea.internal_static_es_fea_ImFea_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.fea.ImgFea.ImFea.class, es.fea.ImgFea.ImFea.Builder.class);
      }

      // Construct using es.fea.ImgFea.ImFea.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        f_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.fea.ImgFea.internal_static_es_fea_ImFea_descriptor;
      }

      public es.fea.ImgFea.ImFea getDefaultInstanceForType() {
        return es.fea.ImgFea.ImFea.getDefaultInstance();
      }

      public es.fea.ImgFea.ImFea build() {
        es.fea.ImgFea.ImFea result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.fea.ImgFea.ImFea buildPartial() {
        es.fea.ImgFea.ImFea result = new es.fea.ImgFea.ImFea(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          f_ = java.util.Collections.unmodifiableList(f_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.f_ = f_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.fea.ImgFea.ImFea) {
          return mergeFrom((es.fea.ImgFea.ImFea)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.fea.ImgFea.ImFea other) {
        if (other == es.fea.ImgFea.ImFea.getDefaultInstance()) return this;
        if (!other.f_.isEmpty()) {
          if (f_.isEmpty()) {
            f_ = other.f_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFIsMutable();
            f_.addAll(other.f_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.fea.ImgFea.ImFea parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.fea.ImgFea.ImFea) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Double> f_ = java.util.Collections.emptyList();
      private void ensureFIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          f_ = new java.util.ArrayList<java.lang.Double>(f_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double f = 1;</code>
       */
      public java.util.List<java.lang.Double>
          getFList() {
        return java.util.Collections.unmodifiableList(f_);
      }
      /**
       * <code>repeated double f = 1;</code>
       */
      public int getFCount() {
        return f_.size();
      }
      /**
       * <code>repeated double f = 1;</code>
       */
      public double getF(int index) {
        return f_.get(index);
      }
      /**
       * <code>repeated double f = 1;</code>
       */
      public Builder setF(
          int index, double value) {
        ensureFIsMutable();
        f_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double f = 1;</code>
       */
      public Builder addF(double value) {
        ensureFIsMutable();
        f_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double f = 1;</code>
       */
      public Builder addAllF(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureFIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, f_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double f = 1;</code>
       */
      public Builder clearF() {
        f_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:es.fea.ImFea)
    }

    // @@protoc_insertion_point(class_scope:es.fea.ImFea)
    private static final es.fea.ImgFea.ImFea DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new es.fea.ImgFea.ImFea();
    }

    public static es.fea.ImgFea.ImFea getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ImFea>
        PARSER = new com.google.protobuf.AbstractParser<ImFea>() {
      public ImFea parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ImFea(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImFea> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImFea> getParserForType() {
      return PARSER;
    }

    public es.fea.ImgFea.ImFea getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImFeaBinArrOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.fea.ImFeaBinArr)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    java.util.List<es.fea.ImgFea.ImFeaBin> 
        getArrList();
    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    es.fea.ImgFea.ImFeaBin getArr(int index);
    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    int getArrCount();
    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    java.util.List<? extends es.fea.ImgFea.ImFeaBinOrBuilder> 
        getArrOrBuilderList();
    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    es.fea.ImgFea.ImFeaBinOrBuilder getArrOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code es.fea.ImFeaBinArr}
   */
  public  static final class ImFeaBinArr extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:es.fea.ImFeaBinArr)
      ImFeaBinArrOrBuilder {
    // Use ImFeaBinArr.newBuilder() to construct.
    private ImFeaBinArr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImFeaBinArr() {
      arr_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImFeaBinArr(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                arr_ = new java.util.ArrayList<es.fea.ImgFea.ImFeaBin>();
                mutable_bitField0_ |= 0x00000001;
              }
              arr_.add(
                  input.readMessage(es.fea.ImgFea.ImFeaBin.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          arr_ = java.util.Collections.unmodifiableList(arr_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.fea.ImgFea.internal_static_es_fea_ImFeaBinArr_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.fea.ImgFea.internal_static_es_fea_ImFeaBinArr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.fea.ImgFea.ImFeaBinArr.class, es.fea.ImgFea.ImFeaBinArr.Builder.class);
    }

    public static final int ARR_FIELD_NUMBER = 1;
    private java.util.List<es.fea.ImgFea.ImFeaBin> arr_;
    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    public java.util.List<es.fea.ImgFea.ImFeaBin> getArrList() {
      return arr_;
    }
    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    public java.util.List<? extends es.fea.ImgFea.ImFeaBinOrBuilder> 
        getArrOrBuilderList() {
      return arr_;
    }
    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    public int getArrCount() {
      return arr_.size();
    }
    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    public es.fea.ImgFea.ImFeaBin getArr(int index) {
      return arr_.get(index);
    }
    /**
     * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
     */
    public es.fea.ImgFea.ImFeaBinOrBuilder getArrOrBuilder(
        int index) {
      return arr_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < arr_.size(); i++) {
        output.writeMessage(1, arr_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < arr_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, arr_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof es.fea.ImgFea.ImFeaBinArr)) {
        return super.equals(obj);
      }
      es.fea.ImgFea.ImFeaBinArr other = (es.fea.ImgFea.ImFeaBinArr) obj;

      boolean result = true;
      result = result && getArrList()
          .equals(other.getArrList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getArrCount() > 0) {
        hash = (37 * hash) + ARR_FIELD_NUMBER;
        hash = (53 * hash) + getArrList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static es.fea.ImgFea.ImFeaBinArr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.fea.ImgFea.ImFeaBinArr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaBinArr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.fea.ImgFea.ImFeaBinArr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaBinArr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFeaBinArr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaBinArr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFeaBinArr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaBinArr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFeaBinArr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(es.fea.ImgFea.ImFeaBinArr prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.fea.ImFeaBinArr}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.fea.ImFeaBinArr)
        es.fea.ImgFea.ImFeaBinArrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.fea.ImgFea.internal_static_es_fea_ImFeaBinArr_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.fea.ImgFea.internal_static_es_fea_ImFeaBinArr_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.fea.ImgFea.ImFeaBinArr.class, es.fea.ImgFea.ImFeaBinArr.Builder.class);
      }

      // Construct using es.fea.ImgFea.ImFeaBinArr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArrFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (arrBuilder_ == null) {
          arr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          arrBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.fea.ImgFea.internal_static_es_fea_ImFeaBinArr_descriptor;
      }

      public es.fea.ImgFea.ImFeaBinArr getDefaultInstanceForType() {
        return es.fea.ImgFea.ImFeaBinArr.getDefaultInstance();
      }

      public es.fea.ImgFea.ImFeaBinArr build() {
        es.fea.ImgFea.ImFeaBinArr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.fea.ImgFea.ImFeaBinArr buildPartial() {
        es.fea.ImgFea.ImFeaBinArr result = new es.fea.ImgFea.ImFeaBinArr(this);
        int from_bitField0_ = bitField0_;
        if (arrBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            arr_ = java.util.Collections.unmodifiableList(arr_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.arr_ = arr_;
        } else {
          result.arr_ = arrBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.fea.ImgFea.ImFeaBinArr) {
          return mergeFrom((es.fea.ImgFea.ImFeaBinArr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.fea.ImgFea.ImFeaBinArr other) {
        if (other == es.fea.ImgFea.ImFeaBinArr.getDefaultInstance()) return this;
        if (arrBuilder_ == null) {
          if (!other.arr_.isEmpty()) {
            if (arr_.isEmpty()) {
              arr_ = other.arr_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArrIsMutable();
              arr_.addAll(other.arr_);
            }
            onChanged();
          }
        } else {
          if (!other.arr_.isEmpty()) {
            if (arrBuilder_.isEmpty()) {
              arrBuilder_.dispose();
              arrBuilder_ = null;
              arr_ = other.arr_;
              bitField0_ = (bitField0_ & ~0x00000001);
              arrBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArrFieldBuilder() : null;
            } else {
              arrBuilder_.addAllMessages(other.arr_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.fea.ImgFea.ImFeaBinArr parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.fea.ImgFea.ImFeaBinArr) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<es.fea.ImgFea.ImFeaBin> arr_ =
        java.util.Collections.emptyList();
      private void ensureArrIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          arr_ = new java.util.ArrayList<es.fea.ImgFea.ImFeaBin>(arr_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          es.fea.ImgFea.ImFeaBin, es.fea.ImgFea.ImFeaBin.Builder, es.fea.ImgFea.ImFeaBinOrBuilder> arrBuilder_;

      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public java.util.List<es.fea.ImgFea.ImFeaBin> getArrList() {
        if (arrBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arr_);
        } else {
          return arrBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public int getArrCount() {
        if (arrBuilder_ == null) {
          return arr_.size();
        } else {
          return arrBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public es.fea.ImgFea.ImFeaBin getArr(int index) {
        if (arrBuilder_ == null) {
          return arr_.get(index);
        } else {
          return arrBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public Builder setArr(
          int index, es.fea.ImgFea.ImFeaBin value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.set(index, value);
          onChanged();
        } else {
          arrBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public Builder setArr(
          int index, es.fea.ImgFea.ImFeaBin.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.set(index, builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public Builder addArr(es.fea.ImgFea.ImFeaBin value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.add(value);
          onChanged();
        } else {
          arrBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public Builder addArr(
          int index, es.fea.ImgFea.ImFeaBin value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.add(index, value);
          onChanged();
        } else {
          arrBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public Builder addArr(
          es.fea.ImgFea.ImFeaBin.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.add(builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public Builder addArr(
          int index, es.fea.ImgFea.ImFeaBin.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.add(index, builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public Builder addAllArr(
          java.lang.Iterable<? extends es.fea.ImgFea.ImFeaBin> values) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, arr_);
          onChanged();
        } else {
          arrBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public Builder clearArr() {
        if (arrBuilder_ == null) {
          arr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          arrBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public Builder removeArr(int index) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.remove(index);
          onChanged();
        } else {
          arrBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public es.fea.ImgFea.ImFeaBin.Builder getArrBuilder(
          int index) {
        return getArrFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public es.fea.ImgFea.ImFeaBinOrBuilder getArrOrBuilder(
          int index) {
        if (arrBuilder_ == null) {
          return arr_.get(index);  } else {
          return arrBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public java.util.List<? extends es.fea.ImgFea.ImFeaBinOrBuilder> 
           getArrOrBuilderList() {
        if (arrBuilder_ != null) {
          return arrBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arr_);
        }
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public es.fea.ImgFea.ImFeaBin.Builder addArrBuilder() {
        return getArrFieldBuilder().addBuilder(
            es.fea.ImgFea.ImFeaBin.getDefaultInstance());
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public es.fea.ImgFea.ImFeaBin.Builder addArrBuilder(
          int index) {
        return getArrFieldBuilder().addBuilder(
            index, es.fea.ImgFea.ImFeaBin.getDefaultInstance());
      }
      /**
       * <code>repeated .es.fea.ImFeaBin arr = 1;</code>
       */
      public java.util.List<es.fea.ImgFea.ImFeaBin.Builder> 
           getArrBuilderList() {
        return getArrFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          es.fea.ImgFea.ImFeaBin, es.fea.ImgFea.ImFeaBin.Builder, es.fea.ImgFea.ImFeaBinOrBuilder> 
          getArrFieldBuilder() {
        if (arrBuilder_ == null) {
          arrBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              es.fea.ImgFea.ImFeaBin, es.fea.ImgFea.ImFeaBin.Builder, es.fea.ImgFea.ImFeaBinOrBuilder>(
                  arr_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          arr_ = null;
        }
        return arrBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:es.fea.ImFeaBinArr)
    }

    // @@protoc_insertion_point(class_scope:es.fea.ImFeaBinArr)
    private static final es.fea.ImgFea.ImFeaBinArr DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new es.fea.ImgFea.ImFeaBinArr();
    }

    public static es.fea.ImgFea.ImFeaBinArr getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ImFeaBinArr>
        PARSER = new com.google.protobuf.AbstractParser<ImFeaBinArr>() {
      public ImFeaBinArr parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ImFeaBinArr(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImFeaBinArr> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImFeaBinArr> getParserForType() {
      return PARSER;
    }

    public es.fea.ImgFea.ImFeaBinArr getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImFeaBinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:es.fea.ImFeaBin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint64 f = 1;</code>
     */
    java.util.List<java.lang.Long> getFList();
    /**
     * <code>repeated uint64 f = 1;</code>
     */
    int getFCount();
    /**
     * <code>repeated uint64 f = 1;</code>
     */
    long getF(int index);
  }
  /**
   * Protobuf type {@code es.fea.ImFeaBin}
   */
  public  static final class ImFeaBin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:es.fea.ImFeaBin)
      ImFeaBinOrBuilder {
    // Use ImFeaBin.newBuilder() to construct.
    private ImFeaBin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImFeaBin() {
      f_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImFeaBin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                f_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              f_.add(input.readUInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                f_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                f_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          f_ = java.util.Collections.unmodifiableList(f_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return es.fea.ImgFea.internal_static_es_fea_ImFeaBin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return es.fea.ImgFea.internal_static_es_fea_ImFeaBin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              es.fea.ImgFea.ImFeaBin.class, es.fea.ImgFea.ImFeaBin.Builder.class);
    }

    public static final int F_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> f_;
    /**
     * <code>repeated uint64 f = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getFList() {
      return f_;
    }
    /**
     * <code>repeated uint64 f = 1;</code>
     */
    public int getFCount() {
      return f_.size();
    }
    /**
     * <code>repeated uint64 f = 1;</code>
     */
    public long getF(int index) {
      return f_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < f_.size(); i++) {
        output.writeUInt64(1, f_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < f_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(f_.get(i));
        }
        size += dataSize;
        size += 1 * getFList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof es.fea.ImgFea.ImFeaBin)) {
        return super.equals(obj);
      }
      es.fea.ImgFea.ImFeaBin other = (es.fea.ImgFea.ImFeaBin) obj;

      boolean result = true;
      result = result && getFList()
          .equals(other.getFList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFCount() > 0) {
        hash = (37 * hash) + F_FIELD_NUMBER;
        hash = (53 * hash) + getFList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static es.fea.ImgFea.ImFeaBin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.fea.ImgFea.ImFeaBin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaBin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static es.fea.ImgFea.ImFeaBin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaBin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFeaBin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaBin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFeaBin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static es.fea.ImgFea.ImFeaBin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static es.fea.ImgFea.ImFeaBin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(es.fea.ImgFea.ImFeaBin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code es.fea.ImFeaBin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:es.fea.ImFeaBin)
        es.fea.ImgFea.ImFeaBinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return es.fea.ImgFea.internal_static_es_fea_ImFeaBin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return es.fea.ImgFea.internal_static_es_fea_ImFeaBin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                es.fea.ImgFea.ImFeaBin.class, es.fea.ImgFea.ImFeaBin.Builder.class);
      }

      // Construct using es.fea.ImgFea.ImFeaBin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        f_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return es.fea.ImgFea.internal_static_es_fea_ImFeaBin_descriptor;
      }

      public es.fea.ImgFea.ImFeaBin getDefaultInstanceForType() {
        return es.fea.ImgFea.ImFeaBin.getDefaultInstance();
      }

      public es.fea.ImgFea.ImFeaBin build() {
        es.fea.ImgFea.ImFeaBin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public es.fea.ImgFea.ImFeaBin buildPartial() {
        es.fea.ImgFea.ImFeaBin result = new es.fea.ImgFea.ImFeaBin(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          f_ = java.util.Collections.unmodifiableList(f_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.f_ = f_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof es.fea.ImgFea.ImFeaBin) {
          return mergeFrom((es.fea.ImgFea.ImFeaBin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(es.fea.ImgFea.ImFeaBin other) {
        if (other == es.fea.ImgFea.ImFeaBin.getDefaultInstance()) return this;
        if (!other.f_.isEmpty()) {
          if (f_.isEmpty()) {
            f_ = other.f_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFIsMutable();
            f_.addAll(other.f_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        es.fea.ImgFea.ImFeaBin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (es.fea.ImgFea.ImFeaBin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Long> f_ = java.util.Collections.emptyList();
      private void ensureFIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          f_ = new java.util.ArrayList<java.lang.Long>(f_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint64 f = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getFList() {
        return java.util.Collections.unmodifiableList(f_);
      }
      /**
       * <code>repeated uint64 f = 1;</code>
       */
      public int getFCount() {
        return f_.size();
      }
      /**
       * <code>repeated uint64 f = 1;</code>
       */
      public long getF(int index) {
        return f_.get(index);
      }
      /**
       * <code>repeated uint64 f = 1;</code>
       */
      public Builder setF(
          int index, long value) {
        ensureFIsMutable();
        f_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 f = 1;</code>
       */
      public Builder addF(long value) {
        ensureFIsMutable();
        f_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 f = 1;</code>
       */
      public Builder addAllF(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureFIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, f_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 f = 1;</code>
       */
      public Builder clearF() {
        f_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:es.fea.ImFeaBin)
    }

    // @@protoc_insertion_point(class_scope:es.fea.ImFeaBin)
    private static final es.fea.ImgFea.ImFeaBin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new es.fea.ImgFea.ImFeaBin();
    }

    public static es.fea.ImgFea.ImFeaBin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ImFeaBin>
        PARSER = new com.google.protobuf.AbstractParser<ImFeaBin>() {
      public ImFeaBin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ImFeaBin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImFeaBin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImFeaBin> getParserForType() {
      return PARSER;
    }

    public es.fea.ImgFea.ImFeaBin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_fea_ImFeaArr_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_es_fea_ImFeaArr_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_fea_ImFea_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_es_fea_ImFea_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_fea_ImFeaBinArr_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_es_fea_ImFeaBinArr_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_fea_ImFeaBin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_es_fea_ImFeaBin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ImgFea.proto\022\006es.fea\"&\n\010ImFeaArr\022\032\n\003ar" +
      "r\030\001 \003(\0132\r.es.fea.ImFea\"\022\n\005ImFea\022\t\n\001f\030\001 \003" +
      "(\001\",\n\013ImFeaBinArr\022\035\n\003arr\030\001 \003(\0132\020.es.fea." +
      "ImFeaBin\"\025\n\010ImFeaBin\022\t\n\001f\030\001 \003(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_es_fea_ImFeaArr_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_es_fea_ImFeaArr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_es_fea_ImFeaArr_descriptor,
        new java.lang.String[] { "Arr", });
    internal_static_es_fea_ImFea_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_es_fea_ImFea_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_es_fea_ImFea_descriptor,
        new java.lang.String[] { "F", });
    internal_static_es_fea_ImFeaBinArr_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_es_fea_ImFeaBinArr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_es_fea_ImFeaBinArr_descriptor,
        new java.lang.String[] { "Arr", });
    internal_static_es_fea_ImFeaBin_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_es_fea_ImFeaBin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_es_fea_ImFeaBin_descriptor,
        new java.lang.String[] { "F", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
