# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/ImFea.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/ImFea.proto',
  package='es.fea',
  syntax='proto2',
  serialized_pb=_b('\n\x14protobuf/ImFea.proto\x12\x06\x65s.fea\"&\n\x08ImFeaArr\x12\x1a\n\x03\x61rr\x18\x01 \x03(\x0b\x32\r.es.fea.ImFea\"\x12\n\x05ImFea\x12\t\n\x01\x66\x18\x01 \x03(\x01\",\n\x0bImFeaBinArr\x12\x1d\n\x03\x61rr\x18\x01 \x03(\x0b\x32\x10.es.fea.ImFeaBin\"\x15\n\x08ImFeaBin\x12\t\n\x01\x66\x18\x01 \x03(\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMFEAARR = _descriptor.Descriptor(
  name='ImFeaArr',
  full_name='es.fea.ImFeaArr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arr', full_name='es.fea.ImFeaArr.arr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=70,
)


_IMFEA = _descriptor.Descriptor(
  name='ImFea',
  full_name='es.fea.ImFea',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f', full_name='es.fea.ImFea.f', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=90,
)


_IMFEABINARR = _descriptor.Descriptor(
  name='ImFeaBinArr',
  full_name='es.fea.ImFeaBinArr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arr', full_name='es.fea.ImFeaBinArr.arr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=136,
)


_IMFEABIN = _descriptor.Descriptor(
  name='ImFeaBin',
  full_name='es.fea.ImFeaBin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f', full_name='es.fea.ImFeaBin.f', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=159,
)

_IMFEAARR.fields_by_name['arr'].message_type = _IMFEA
_IMFEABINARR.fields_by_name['arr'].message_type = _IMFEABIN
DESCRIPTOR.message_types_by_name['ImFeaArr'] = _IMFEAARR
DESCRIPTOR.message_types_by_name['ImFea'] = _IMFEA
DESCRIPTOR.message_types_by_name['ImFeaBinArr'] = _IMFEABINARR
DESCRIPTOR.message_types_by_name['ImFeaBin'] = _IMFEABIN

ImFeaArr = _reflection.GeneratedProtocolMessageType('ImFeaArr', (_message.Message,), dict(
  DESCRIPTOR = _IMFEAARR,
  __module__ = 'protobuf.ImFea_pb2'
  # @@protoc_insertion_point(class_scope:es.fea.ImFeaArr)
  ))
_sym_db.RegisterMessage(ImFeaArr)

ImFea = _reflection.GeneratedProtocolMessageType('ImFea', (_message.Message,), dict(
  DESCRIPTOR = _IMFEA,
  __module__ = 'protobuf.ImFea_pb2'
  # @@protoc_insertion_point(class_scope:es.fea.ImFea)
  ))
_sym_db.RegisterMessage(ImFea)

ImFeaBinArr = _reflection.GeneratedProtocolMessageType('ImFeaBinArr', (_message.Message,), dict(
  DESCRIPTOR = _IMFEABINARR,
  __module__ = 'protobuf.ImFea_pb2'
  # @@protoc_insertion_point(class_scope:es.fea.ImFeaBinArr)
  ))
_sym_db.RegisterMessage(ImFeaBinArr)

ImFeaBin = _reflection.GeneratedProtocolMessageType('ImFeaBin', (_message.Message,), dict(
  DESCRIPTOR = _IMFEABIN,
  __module__ = 'protobuf.ImFea_pb2'
  # @@protoc_insertion_point(class_scope:es.fea.ImFeaBin)
  ))
_sym_db.RegisterMessage(ImFeaBin)


# @@protoc_insertion_point(module_scope)
